### ISSUE TITLE
Let repo-owners mark assignment as "done"

### ISSUE THREAD

**Issue by kyzn** [kyzn/PRC#18]
Currently only assignee can mark it as "done". Consider giving repo-owners the power of marking it as done.

**Comment by kyzn** [comment]
Also consider automating "mark as done" functionality. Set a cronjob, check once/day or once/week. Also check one last time before giving out new assignments.

**Comment by JJ** [comment]
If you can do that, it would be great.

**Comment by choroba** [comment]
Some people might want to submit more than 1 PR. I think we shouldn't close their assignment automatically before the end of the month.

**Comment by kyzn** [comment]
Thanks for the feedback! I think I had enough people mention the same scenario, so it's probably better if we kept "DONE" button.
We can still consider adding an option to user settings: "Let owners of my assignment repos click DONE".
