### ISSUE TITLE
Admin pages

### ISSUE THREAD

**Issue by kyzn** [kyzn/PRC#19]
Build admin pages so that I don't have to query database manually all the time to get basic stats.
Make sure to authorize only admins (currently just me).

v1, just view:
- /admin/users
  - filters
- /admin/user/id
  - shows db fields (github_login, last_login_time, tos agreement etc)
  - shows repos, assignments with links
- /admin/repos
  - filters
- /admin/repo/id
  - shows db fields (accepting_assignees, gone_missing etc)
  - shows owner, assignments and assignees with links
- /admin/assignments
  - filters
- /admin/assignment/id
  - shows db fields (month, status etc)
  - shows assignee, repo, repo owner with links

v2, some editing:
- force reload repos
- update an assignment with a different repo
- update assignment status (for cases like "I clicked skip by mistake")

v3:
- add new assignment

**Comment by gabru-md** [comment]
I would like to try adding the routes to the project. This way I can learn about the Catalyst framework and improve my Perl understanding.
Can I start with just adding the` /admin/users` route first? I'll work on more once I get a hold of it?
:sweat_smile:

**Comment by kyzn** [comment]
Sure thing! Please go ahead. You can start without filters: Just a page that lists all users. I'd recommend creating a new controller named "Admin". Let me know if you have any questions.

**Comment by gabru-md** [comment]
so far I've done the following changes. I've worked out the controller part and now will be working on adding the admin authentication to it.

![ss2](https://user-images.githubusercontent.com/25414121/53653723-fb80bd00-3c71-11e9-962a-f00bcdcce79f.png)
![ss1_prc](https://user-images.githubusercontent.com/25414121/53653725-fb80bd00-3c71-11e9-954d-3459e12a02a3.png)

**Comment by gabru-md** [comment]
@kyzn for the repos to be shown in the `/admin/user/{id}`
- should we show all the repositories that the user has?
- or should we only show the repositories that currently accept assignees?
- or show all the repositories and if it is accepting assignees?

similar doubt for the `/admin/repo` route as well.

**Comment by kyzn** [comment]
I'll get back to you after 3/12
