### ISSUE TITLE
Add some description and screenshot to readme

### ISSUE THREAD

**Issue by kyzn** [kyzn/PRC#3]

**Comment by gabru-md** [comment]
Hello @kyzn I would like to help with this project. Can I take this up?

**Comment by kyzn** [comment]
Hi @gabru-md! Sure thing, go ahead. What I had in mind for this tickets is, just getting one logged in screenshot from pullrequest.club, and perhaps bring a little piece of description for newcomers. pullrequest.club/help could be useful. Oh and we can use a link to site as well.

Out of curiousity -- did you find the project through Google Summer of Code?

**Comment by gabru-md** [comment]
sure I'd provide you with a PR.

about the project,  I was looking for a perl based project to contribute to and found this on the GSOC website. I've been a successful GSOC student in the last year. I just wanted to be a part of a perl project to i prove my understanding of this language. So my aim is to learn with this project and not GSOC this time. :sweat_smile:

**Comment by kyzn** [comment]
Sounds good! Let me know if you have any questions.
