### ISSUE TITLE
Don't talk to GitHub at each load of /my-repos

### ISSUE THREAD

**Issue by kyzn** [kyzn/PRC#9]
Perhaps limit to once a day. Consider adding a "pull" or "refresh" button.

**Comment by choroba** [comment]
Hi, I'm playing with this issue in scope of my January PRC assignment. I've already implemented the once a day limit, you can check [here](https://github.com/choroba/PRC/commit/fa7dc6c8189405c9bbf801ec76939890c6cbaa51).
I'm not much familiar with DBIx::Class, though. How does one update the schema of an already running application? Or does it work by itself out of the box? My local app didn't seem to add the column after I had edited the files. I had to run
```sql
ALTER TABLE user ADD COLUMN last_repos_sync DATETIME DEFAULT NULL;
```
manually in sqlite3.

I haven't yet added the "Refresh" button, but it seems the easiest part of the issue.

**Comment by kyzn** [comment]
Hi @choroba! Thanks a lot for your work. Your commit https://github.com/choroba/PRC/commit/fa7dc6c8189405c9bbf801ec76939890c6cbaa51 looks great to me.

Regarding your question, I don't think it will work out by itself: Unfortunately I don't have a database migration system in place. I just keep existing table definitions in `prc.sql`. So I will have to run what you pasted above manually.

Also on "refresh" button: It was just an idea, but I'm open to suggestions: Do you think adding that button would be helpful? I thought it might come handy if users had a way to "force reload"..

**Comment by choroba** [comment]
I think the button is helpful. Imagine a user creates a new repository, they probably don't want to wait until tomorrow to offer it for pull requests, and moreover, they probably don't remember what repositories they created yesterday and wanted to offer today. They just want to reload the repositories and check the new one.
See the pull request for a solution.

**Comment by kyzn** [comment]
That makes sense, thanks! I will review & merge the PR in a moment.
